name: atbeach_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  intro_slider: ^3.0.7

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/illustration/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Regular.ttf
          weight: 500
        - asset: fonts/Poppins-Medium.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
